#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "vikunja"
name = "Vikunja"
description.en = "Self-hosted To-Do list application"
description.fr = "Application de liste de tâches auto-hébergée"

version = "2.6.0~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://vikunja.io/"
demo = "https://try.vikunja.io/login"
admindoc = "https://vikunja.io/docs/"
code = "https://github.com/go-vikunja/vikunja"
fund = "https://www.buymeacoffee.com/kolaente"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "1500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If 'visitors', Vikunja will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si 'visiteurs', Vikunja sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr-FR"]
    default = "fr-FR"

[resources]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://github.com/go-vikunja/vikunja/releases/download/v2.6.0/vikunja-v2.6.0-linux-amd64-full.zip"
        amd64.sha256 = "44f55c5620cf90f9f125ee2d2fda31db1946230da6d1dbc0f7943aed68db4264"
        arm64.url = "https://github.com/go-vikunja/vikunja/releases/download/v2.6.0/vikunja-v2.6.0-linux-arm64-full.zip"
        arm64.sha256 = "b30e0ef2ba86ed1138a53097dc386eb0ac42483f85526325687f909c3430477b"
        armhf.url = "https://github.com/go-vikunja/vikunja/releases/download/v2.6.0/vikunja-v2.6.0-linux-arm-7-full.zip"
        armhf.sha256 = "8b91a9b3c6f0fcf95b31d23ef9fa6a726d6d7a54e5aa69c9ac88a5c04bae7067"
        in_subdir = false
        format = "zip"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = 'vikunja-.*-linux-amd64-full.zip'
        autoupdate.asset.arm64 = 'vikunja-.*-linux-arm64-full.zip'
        autoupdate.asset.armhf = 'vikunja-.*-linux-arm-7-full.zip'

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]
    
    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"
    api.auth_header = false

    [resources.ports]
    
    [resources.apt]
    packages = ["postgresql", "redis-server"]

    [resources.database]
    type = "postgresql"
