#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

timezone="$(cat /etc/timezone)"
secret=$(ynh_string_random --length=32)
redis_db=$(ynh_redis_get_free_db)

set_motd=""
enable_registration="true"
enable_linksharing="true"
enable_taskattachments="true"
enable_taskcomments="true"
enable_emailreminders="true"
enable_userdeletion="true"
maxavatarsize=1024
maxitemsperpage=50

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --app=$app --key=set_motd --value=$set_motd
ynh_app_setting_set --app=$app --key=enable_registration --value=$enable_registration
ynh_app_setting_set --app=$app --key=enable_linksharing --value=$enable_linksharing
ynh_app_setting_set --app=$app --key=enable_taskattachments --value=$enable_taskattachments
ynh_app_setting_set --app=$app --key=enable_taskcomments --value=$enable_taskcomments
ynh_app_setting_set --app=$app --key=enable_emailreminders --value=$enable_emailreminders
ynh_app_setting_set --app=$app --key=enable_userdeletion --value=$enable_userdeletion
ynh_app_setting_set --app=$app --key=maxavatarsize --value=$maxavatarsize
ynh_app_setting_set --app=$app --key=maxitemsperpage --value=$maxitemsperpage

#=================================================
# INSTALL BACKEND
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"
executable="$(find $tempdir -name "vikunja-*" \! -name "*.sha256")"
ln -s "$executable" "$install_dir/vikunja"

chmod +x "$install_dir/vikunja"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="config.yml" --destination="$install_dir/config.yml"

chmod 400 "$install_dir/config.yml"
chown "$app:$app" "$install_dir/config.yml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

ynh_add_nginx_config

ynh_add_systemd_config

yunohost service add $app --description="Self-hosted To-Do list application" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..." --weight=2

# Start a systemd service
ynh_systemd_action --service_name="$app" --action=start --log_path=systemd #--line_match="server started on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
