#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

timezone="$(cat /etc/timezone)"
secret=$(ynh_string_random --length=32)
redis_db=$(ynh_redis_get_free_db)

set_motd=""
enable_registration="true"
enable_linksharing="true"
enable_taskattachments="true"
enable_taskcomments="true"
enable_emailreminders="true"
enable_userdeletion="true"
maxavatarsize=1024
maxitemsperpage=50

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=set_motd --value=$set_motd
ynh_app_setting_set --key=enable_registration --value=$enable_registration
ynh_app_setting_set --key=enable_linksharing --value=$enable_linksharing
ynh_app_setting_set --key=enable_taskattachments --value=$enable_taskattachments
ynh_app_setting_set --key=enable_taskcomments --value=$enable_taskcomments
ynh_app_setting_set --key=enable_emailreminders --value=$enable_emailreminders
ynh_app_setting_set --key=enable_userdeletion --value=$enable_userdeletion
ynh_app_setting_set --key=maxavatarsize --value=$maxavatarsize
ynh_app_setting_set --key=maxitemsperpage --value=$maxitemsperpage

#=================================================
# INSTALL Vikunja
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
executable="$(find $install_dir -name "vikunja-*" \! -name "*.sha256")"
mv "$executable" "$install_dir/vikunja"

chmod +x "$install_dir/vikunja"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.yml" --destination="$install_dir/config.yml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Self-hosted To-Do list application" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action=start --log_path=systemd --wait_until="server started on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
